FROM ubuntu:latest


RUN mkdir -p /usr/src/project/
WORKDIR /usr/src/project/


RUN apt-get update -y
RUN apt install npm -y
# RUN npm install create-react-app
# RUN npm install react-router-dom
# RUN npm install axios


EXPOSE 3000
CMD ["sh","/usr/src/project/run.sh"]
