FROM ubuntu:latest


RUN mkdir -p /usr/src/project/
WORKDIR /usr/src/project/


RUN apt-get update -y
RUN apt install npm -y
RUN npm install -g create-reate-app
RUN npm install react-router-dom
RUN npm install axios
Run npm install router

# npm run start


EXPOSE 5000
CMD ["sh","/usr/src/project/run.sh"]









