FROM node:14.4.0-stretch

WORKDIR /app/frontend

# Install dependencies
# COPY package.json yarn.lock /app/

# RUN npm install

# Add rest of the client code
COPY . /app/frontend
RUN npm install

EXPOSE 3000

# sudo docker run -it -p 3000:3000 frontend