version: '3.2'

services:
  server:
    build: ./server
    tty: true
    volumes:
      -  ./server:/app/server
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db


  client:
    build: ./client
    tty: true
    volumes:
      - ./client:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    command: npm start
    environment:
      COMPOSE_HTTP_TIMEOUT: 360

  db:
    image: "postgres:12"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
    - "dbdata:/app/db"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgbackups:
    container_name: Backup_ldap
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@every 0h30m00s
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

volumes:
  dbdata:


#docker-compose up --build