version: '3'

services:
  db2:
    build: ./db
    tty: true
    
    volumes: 
      -  /home/yura/PycharmProjects/micran/db/data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - TZ=Europe/Stockholm
    command: >
       sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
       echo $TZ > /etc/timezone"


  
  server:
    build: ./server
    tty: true
    volumes:
      -  /home/yura/PycharmProjects/micran/server:/usr/src/server/
    ports:
      - "8000:8000"
    depends_on:
      - db2
#    command: ls
    command:
       sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
       echo $TZ > /etc/timezone &&
       sh /usr/src/server/run.sh"
    environment:
      - TZ=Europe/Stockholm




  client:
    build: ./client
    tty: true
    volumes:
      - /home/yura/PycharmProjects/micran/client:/usr/src/project/
    ports:
      - "5000:5000"
    depends_on:
      - db2
    command:
     sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
     echo $TZ > /etc/timezone &&
     sh /usr/src/project/run.sh"
    environment:
      - TZ=Europe/Stockholm

volumes:
  db2:


    

#docker-compose up -d