version: '3'

services:
  server:
    build: ./server
    tty: true
    volumes:
      -  ./server:/app/server
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000


  client:
    build: ./client
    tty: true
    volumes:
      - ./client:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    command: npm start

    

#docker-compose up -d