version: '3.2'

services:
  server:
    build: ./server
    tty: true
    volumes:
      -  ./server:/app/server
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db


  client:
    build: ./client
    tty: true
    volumes:
      - ./client:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    command: npm start

  db:
    image: "postgres:13"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
    - /app/db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres



#docker-compose up --build