version: '3'

services:
  db2:
    build: ./db
    tty: true
    
    volumes: 
      -  /home/yura/Documents/python/work/micran_demo/micran/db/data:/var/lib/postgresql
    ports:
      - "5430:5432"


  
  server:
    build: ./server
    tty: true
    volumes:
      -  /home/yura/Documents/python/work/micran_demo/micran/server:/usr/src/server/
    ports:
      - "8000:8000"
    depends_on:
      - db2
#    command: ls 
    command: sh /usr/src/server/run.sh




  client:
    build: ./client
    tty: true
    volumes:
      - /home/yura/Documents/python/work/micran_demo/micran/client:/usr/src/project/
    ports:
      - "3000:3000"
    depends_on:
      - db2
    command: sh /usr/src/project/run.sh    



    

#docker-compose up -d