version: '3'

services:
  db2:
    build: ./db
    tty: true
    
    volumes: 
      - C:/python/micran2/db/data:/var/lib/postgresql
    ports:
      - "5432:5432"


  
  server:
    build: ./server
    tty: true
    volumes:
      - C:/python/micran2/server:/usr/src/server/
    ports:
      - "8000:8000"
    depends_on:
      - db2
#    command: ls 
    command: sh /usr/src/server/run.sh




  client:
    build: ./client
    tty: true
    volumes:
      - C:/python/micran2/client:/usr/src/project/
    ports:
      - "5000:5000"
    depends_on:
      - db2
    command: sh /usr/src/project/run.sh    



    

#docker-compose up -d