# Generated by Django 3.0.5 on 2020-06-04 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('access_lvl', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(max_length=5)),
                ('subdivision', models.CharField(max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('position', models.CharField(max_length=30)),
                ('experience', models.FloatField(default='0.0')),
                ('shift', models.CharField(max_length=30)),
                ('part_time_job', models.CharField(max_length=30)),
                ('lateness', models.CharField(max_length=30)),
                ('group', models.ForeignKey(blank=True, default='None', on_delete=django.db.models.deletion.PROTECT, to='cabinet.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500)),
                ('hour', models.FloatField(blank=True)),
                ('project', models.CharField(blank=True, max_length=50)),
                ('curator', models.CharField(blank=True, default=None, max_length=50)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('tasks', models.CharField(blank=True, max_length=500)),
                ('is_done', models.BooleanField(blank=True, default=False)),
                ('participants', models.ManyToManyField(blank=True, to='cabinet.Profile')),
            ],
        ),
    ]
