# Generated by Django 3.0 on 2020-08-18 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=30)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(blank=True, max_length=50)),
                ('department_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=30)),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('login', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sex', models.CharField(blank=True, max_length=5)),
                ('subdivision', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('experience', models.FloatField(default='0.0')),
                ('shift', models.CharField(blank=True, max_length=30)),
                ('part_time_job', models.CharField(blank=True, max_length=30)),
                ('lateness', models.CharField(blank=True, max_length=30)),
                ('SRI_SAS', models.BooleanField(blank=True, default='False')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_id', to='cabinet.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('client', models.CharField(blank=True, max_length=100)),
                ('production_order', models.CharField(blank=True, max_length=100)),
                ('comment_for_employees', models.TextField(blank=True)),
                ('contract', models.CharField(max_length=100)),
                ('type', models.BooleanField(blank=True, default='False')),
                ('status', models.BooleanField(blank=True, default='False')),
                ('report_availability', models.BooleanField(blank=True, default='False')),
                ('acceptance_vp', models.BooleanField(blank=True, default='False')),
                ('chief_designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chief_designer_id', to='cabinet.Profile')),
                ('deputy_chief_designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deputy_chief_designer_id', to='cabinet.Profile')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_id', to='cabinet.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_norm_common', models.FloatField(blank=True, default=0)),
                ('time_norm_common', models.FloatField(blank=True, default=0)),
                ('date', models.DateField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, default=0)),
                ('orion_id', models.IntegerField(blank=True, default=0)),
                ('intellect_id', models.IntegerField(blank=True, default=0)),
                ('leaving', models.TimeField(blank=True)),
                ('late', models.TimeField(blank=True)),
                ('fine_late', models.TimeField(blank=True)),
                ('hooky', models.TimeField(blank=True)),
                ('hours_worked', models.TimeField(blank=True)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdepartment', models.CharField(blank=True, max_length=50)),
                ('subdepartment_name', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.FloatField(blank=True, default=0)),
                ('vacation', models.FloatField(blank=True, default=0)),
                ('sick_leave', models.FloatField(blank=True, default=0)),
                ('day_off', models.FloatField(blank=True, default=0)),
                ('time_from_report', models.FloatField(blank=True, default=0)),
                ('time_orion', models.FloatField(blank=True, default=0)),
                ('time_norm', models.FloatField(blank=True, default=0)),
                ('time_off', models.FloatField(blank=True, default=0)),
                ('plan_salary', models.FloatField(blank=True, default=0)),
                ('award', models.FloatField(blank=True, default=0)),
                ('penalty', models.FloatField(blank=True, default=0)),
                ('is_penalty', models.BooleanField(blank=True, default=0)),
                ('salary_hand', models.FloatField(blank=True, default=0)),
                ('date', models.DateField(blank=True)),
                ('common_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.SalaryCommon')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('hour', models.FloatField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.Profile')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_id', to='cabinet.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('available_actions', models.ManyToManyField(blank=True, to='cabinet.Action')),
                ('participants', models.ManyToManyField(blank=True, to='cabinet.Profile')),
            ],
        ),
    ]
