# Generated by Django 3.0.5 on 2020-05-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='creator',
            new_name='creator_id',
        ),
    ]
