# Generated by Django 3.0 on 2020-08-18 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='fine_late',
            field=models.TimeField(blank=True, default='09:00:00'),
        ),
    ]
