# Generated by Django 3.0 on 2020-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_remove_action_action_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
