# Generated by Django 3.0.5 on 2020-06-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20200610_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
    ]
