# Generated by Django 3.0 on 2020-08-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20200818_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subdivision',
        ),
        migrations.AddField(
            model_name='profile',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdepartment_id', to='cabinet.Subdepartment'),
        ),
    ]
