# Generated by Django 3.0 on 2020-07-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_action_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_norm', models.FloatField(blank=True)),
                ('days_worked', models.FloatField(blank=True)),
                ('vacation', models.FloatField(blank=True)),
                ('sick_leave', models.FloatField(blank=True)),
                ('day_off', models.FloatField(blank=True)),
                ('time_report', models.FloatField(blank=True)),
                ('time_norm', models.FloatField(blank=True)),
                ('time_orion', models.FloatField(blank=True)),
                ('plan_salary', models.FloatField(blank=True)),
                ('award', models.FloatField(blank=True)),
                ('salary_hand', models.FloatField(blank=True)),
            ],
        ),
    ]
