# Generated by Django 3.0.5 on 2020-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20200420_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
