# Generated by Django 3.0 on 2020-08-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20200818_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direction_id', to='cabinet.Direction'),
        ),
    ]
