# Generated by Django 3.0.5 on 2020-06-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_remove_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='access_lvl',
        ),
        migrations.AddField(
            model_name='group',
            name='available_actions',
            field=models.ManyToManyField(to='cabinet.Action'),
        ),
    ]
