# Generated by Django 3.0 on 2020-07-09 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.Profile'),
            preserve_default=False,
        ),
    ]
