# Generated by Django 3.0.5 on 2020-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20200420_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, default=None, related_name='participants', to='cabinet.Profile'),
        ),
    ]
