# Generated by Django 3.0.5 on 2020-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_auto_20200420_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lateness',
            field=models.CharField(max_length=30),
        ),
    ]
