# Generated by Django 3.0.5 on 2020-05-09 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_auto_20200503_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lifespan',
        ),
    ]
