# Generated by Django 3.0 on 2020-08-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_calendarmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarmark',
            name='type',
            field=models.CharField(blank=True, choices=[('undefined', 'undefined'), ('paid_holiday', 'paid_holiday'), ('unpaid_holiday', 'unpaid_holiday'), ('sick_leave', 'sick_leave'), ('hooky', 'hooky'), ('event', 'event'), ('study_holiday', 'study_holiday'), ('planned_holiday', 'planned_holiday')], max_length=50),
        ),
    ]
