# Generated by Django 3.0.7 on 2020-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_auto_20200616_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
