# Generated by Django 3.0 on 2020-08-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_auto_20200818_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Subdepartment'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_id', to='cabinet.Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subdepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartment_id', to='cabinet.Subdepartment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chief_designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_designer_id', to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deputy_chief_designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_chief_designer_id', to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_id', to='cabinet.Direction'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_id', to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='creator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_id', to='cabinet.Project'),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='common_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.SalaryCommon'),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Department'),
        ),
    ]
