# Generated by Django 3.0.5 on 2020-05-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0007_remove_project_lifespan'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='curator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='cabinet.Profile'),
        ),
    ]
