# Generated by Django 3.0 on 2020-07-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_auto_20200714_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='project',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='acceptance_vp',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AddField(
            model_name='project',
            name='chief_designer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='comment_for_employees',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='deputy_chief_designer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='direction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='production_order',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='report_availability',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], max_length=15),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('CLOSE', 'Close'), ('OPEN', 'Open')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('INTERIOR', 'Interior'), ('EXTERNAL', 'External')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
