# Generated by Django 3.0.5 on 2020-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0008_report_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='curator',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
