# Generated by Django 3.0.5 on 2020-05-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_auto_20200513_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='curator',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
