# Generated by Django 3.0.7 on 2020-06-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0009_auto_20200618_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='available_actions',
            field=models.ManyToManyField(blank=True, to='cabinet.Action'),
        ),
    ]
