# Generated by Django 3.0 on 2020-07-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0010_auto_20200715_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
