# Generated by Django 3.0 on 2020-09-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0011_auto_20200819_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subdepartment',
        ),
        migrations.AddField(
            model_name='department',
            name='subdepartment_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='direction',
            name='subdepartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabinet.Department'),
        ),
        migrations.DeleteModel(
            name='Subdepartment',
        ),
    ]
