# Generated by Django 3.0 on 2020-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_auto_20200715_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departament',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
