# Generated by Django 3.0 on 2020-07-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0012_auto_20200702_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField()),
                ('login', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
    ]
