# Generated by Django 3.0 on 2020-07-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0013_auto_20200707_0302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
