# Generated by Django 3.0 on 2020-09-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_auto_20200910_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ban_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ban', to='cabinet.Profile'),
        ),
    ]
