# Generated by Django 3.0 on 2020-07-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0014_auto_20200707_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='action',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
