# Generated by Django 3.0 on 2020-07-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_auto_20200716_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='curator',
        ),
    ]
