# Generated by Django 3.0 on 2020-07-09 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0015_logging_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='logging',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
