# Generated by Django 3.0 on 2020-09-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_report_check_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
