# Generated by Django 3.0 on 2020-07-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0016_remove_report_curator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCommon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_norm_common', models.FloatField(blank=True)),
                ('time_norm_common', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_worked', models.FloatField(blank=True)),
                ('vacation', models.FloatField(blank=True)),
                ('sick_leave', models.FloatField(blank=True)),
                ('day_off', models.FloatField(blank=True)),
                ('time_from_report', models.FloatField(blank=True)),
                ('time_orion', models.FloatField(blank=True)),
                ('plan_salary', models.FloatField(blank=True)),
                ('award', models.FloatField(blank=True)),
                ('is_awarded', models.BooleanField(blank=True)),
                ('salary_hand', models.FloatField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('common_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.SalaryCommon')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
