# Generated by Django 3.0 on 2020-09-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0017_report_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fine_late',
            field=models.TimeField(default='09:15:00'),
        ),
    ]
