# Generated by Django 3.0 on 2020-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_salaryindividual_time_norm'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryindividual',
            name='time_off',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
