# Generated by Django 3.0 on 2020-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0018_profile_fine_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oklad',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
