# Generated by Django 3.0 on 2020-07-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0019_salaryindividual_time_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='award',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='common_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cabinet.SalaryCommon'),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='day_off',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='days_worked',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='is_awarded',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='plan_salary',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='salary_hand',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='sick_leave',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='time_from_report',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='time_norm',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='time_off',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='time_orion',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='vacation',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
