# Generated by Django 3.0 on 2020-07-21 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet', '0020_auto_20200721_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_id', to='cabinet.Project'),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='common_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cabinet.SalaryCommon'),
        ),
        migrations.AlterField(
            model_name='salaryindividual',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.Profile'),
        ),
    ]
