# Generated by Django 3.0 on 2020-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0021_remove_group_available_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('available_actions', models.ManyToManyField(blank=True, to='cabinet.Action')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='available_actions',
            field=models.ManyToManyField(blank=True, to='cabinet.GroupAction'),
        ),
    ]
