# Generated by Django 3.0 on 2020-07-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0022_salarycommon_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycommon',
            name='days_norm_common',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='salarycommon',
            name='time_norm_common',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
