# Generated by Django 3.0 on 2020-09-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0022_auto_20200915_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='available_actions',
            new_name='actions',
        ),
    ]
