# Generated by Django 3.0 on 2020-09-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0023_auto_20200915_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='actions',
            field=models.ManyToManyField(blank=True, to='cabinet.Action'),
        ),
    ]
