# Generated by Django 3.0 on 2020-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0023_auto_20200722_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
