# Generated by Django 3.0 on 2020-07-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0024_auto_20200723_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryindividual',
            name='is_penalty',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='salaryindividual',
            name='penalty',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
