# Generated by Django 3.0 on 2020-09-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0024_auto_20200915_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupaction',
            name='description',
        ),
    ]
