# Generated by Django 3.0 on 2020-07-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0025_auto_20200728_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryindividual',
            name='is_awarded',
        ),
    ]
