# Generated by Django 3.0 on 2020-07-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0026_remove_salaryindividual_is_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycommon',
            name='date',
            field=models.DateField(blank=True, unique=True),
        ),
    ]
