# Generated by Django 3.0 on 2020-09-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0026_auto_20200916_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fine_late',
            field=models.TimeField(blank=True, default='09:15:00'),
        ),
    ]
