# Generated by Django 3.0 on 2020-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0027_auto_20200730_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryindividual',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
