# Generated by Django 3.0 on 2020-09-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0027_auto_20200916_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
