# Generated by Django 3.0 on 2020-08-03 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0029_auto_20200730_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryindividual',
            name='common_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.SalaryCommon'),
        ),
    ]
