# Generated by Django 3.0 on 2020-10-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0030_auto_20200930_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
