# Generated by Django 3.0 on 2020-08-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0030_auto_20200803_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='SRI_SAS',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
