# Generated by Django 3.0 on 2020-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0031_profile_sri_sas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_availability',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(blank=True, default='False'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.BooleanField(blank=True, default='False'),
        ),
    ]
