# Generated by Django 3.0 on 2020-08-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0032_auto_20200812_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='chief_designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chief_designer_id', to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deputy_chief_designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deputy_chief_designer_id', to='cabinet.Profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_id', to='cabinet.Profile'),
        ),
    ]
