# Generated by Django 3.0 on 2020-10-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0032_auto_20201005_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaction',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
