# Generated by Django 3.0 on 2020-08-17 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0034_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdepartment_code', models.CharField(max_length=50)),
                ('subdepartment_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departament_id', to='cabinet.Departament'),
        ),
    ]
