# Generated by Django 3.0 on 2020-08-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0035_auto_20200817_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(max_length=100),
        ),
    ]
