FROM ubuntu:20.04

WORKDIR /app/server

COPY requirements.txt /app/server
RUN apt-get update && apt-get install libsasl2-dev python-dev libldap2-dev libssl-dev -y && apt install python3-pip -y
RUN pip3 install --upgrade pip -r requirements.txt
COPY . /app/server

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
# sudo docker run -it -p 8000:8000 backend
